create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, username text unique not null, display_name text not null default 'KL Student', avatar_url text, bio text, branch text, created_at timestamptz not null default now());
create table if not exists public.posts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, caption text, media_url text, created_at timestamptz not null default now());
create table if not exists public.likes(post_id uuid references public.posts(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(post_id,user_id));
create table if not exists public.comments(id uuid primary key default gen_random_uuid(),post_id uuid references public.posts(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,body text not null,created_at timestamptz not null default now());
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now());
create table if not exists public.conversation_members(conversation_id uuid references public.conversations(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,primary key(conversation_id,user_id));
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid references public.conversations(id) on delete cascade,sender_id uuid references public.profiles(id) on delete cascade,body text not null,created_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,actor_id uuid references public.profiles(id) on delete cascade,type text not null,post_id uuid references public.posts(id) on delete cascade,is_read boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.community_members(user_id uuid primary key references auth.users(id) on delete cascade,joined_at timestamptz not null default now());
create table if not exists public.invite_codes(code text primary key,max_uses int not null default 3000,uses int not null default 0,active boolean not null default true,created_at timestamptz not null default now());
insert into public.invite_codes(code) values('KLVIBE26') on conflict do nothing;

alter table public.profiles enable row level security; alter table public.posts enable row level security; alter table public.likes enable row level security; alter table public.comments enable row level security; alter table public.conversations enable row level security; alter table public.conversation_members enable row level security; alter table public.messages enable row level security; alter table public.notifications enable row level security; alter table public.community_members enable row level security; alter table public.invite_codes enable row level security;

create policy profiles_read on public.profiles for select to authenticated using (true); create policy profiles_write on public.profiles for insert to authenticated with check(id=auth.uid()); create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy posts_read on public.posts for select to authenticated using(true); create policy posts_write on public.posts for insert to authenticated with check(user_id=auth.uid()); create policy posts_update on public.posts for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy posts_delete on public.posts for delete to authenticated using(user_id=auth.uid());
create policy likes_read on public.likes for select to authenticated using(true); create policy likes_write on public.likes for insert to authenticated with check(user_id=auth.uid()); create policy likes_delete on public.likes for delete to authenticated using(user_id=auth.uid());
create policy comments_read on public.comments for select to authenticated using(true); create policy comments_write on public.comments for insert to authenticated with check(user_id=auth.uid()); create policy comments_delete on public.comments for delete to authenticated using(user_id=auth.uid());
create policy cm_read on public.conversation_members for select to authenticated using(user_id=auth.uid());
create policy conv_read on public.conversations for select to authenticated using(exists(select 1 from public.conversation_members cm where cm.conversation_id=id and cm.user_id=auth.uid()));
create policy msg_read on public.messages for select to authenticated using(exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid())); create policy msg_write on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.conversation_members cm where cm.conversation_id=conversation_id and cm.user_id=auth.uid()));
create policy notif_read on public.notifications for select to authenticated using(user_id=auth.uid()); create policy notif_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy community_read on public.community_members for select to authenticated using(true); create policy community_insert on public.community_members for insert to authenticated with check(user_id=auth.uid());

after insert on auth.users create trigger kl_profile_trigger execute function public.kl_new_profile();
